# Generated by Django 2.0 on 2020-01-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchase',
            table='purchases',
        ),
    ]
