# Generated by Django 2.0 on 2020-01-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_item_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'price')},
        ),
    ]
