# Generated by Django 2.0 on 2020-01-21 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20200120_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_item', to='shops.Item'),
        ),
        migrations.AlterField(
            model_name='store',
            name='followed_by',
            field=models.ManyToManyField(blank=True, default=[], related_name='followed_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='items',
            field=models.ManyToManyField(blank=True, default=[], related_name='stores', to='shops.Item'),
        ),
    ]
