# Generated by Django 2.1.5 on 2020-01-22 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20200122_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='followed_by',
            field=models.ManyToManyField(blank=True, default=[], related_name='followed_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='followed_by',
            field=models.ManyToManyField(blank=True, default=[], null=True, related_name='followed_items',
                                         to=settings.AUTH_USER_MODEL),
        ),
    ]
